version: '3.9'
services:
  db:
    image: postgres:15
    container_name: university-db
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brant
    ports:
      - "5433:5433"

  app:
    build: .
    container_name: university-app
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/university
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: brant
